# Generated by Django 5.0.6 on 2024-07-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='weekday',
            field=models.CharField(max_length=12, null=True, verbose_name='Weekday'),
        ),
    ]
