# Generated by Django 5.0.6 on 2024-07-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0002_day_weekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='user',
        ),
        migrations.AddField(
            model_name='day',
            name='user',
            field=models.ManyToManyField(to='mycalendar.user'),
        ),
    ]
