# Generated by Django 5.0.6 on 2024-07-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0003_remove_day_user_day_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(editable=False, verbose_name='Date'),
        ),
    ]
