# Generated by Django 5.0.6 on 2024-07-03 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0007_alter_day_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('shift', models.SmallIntegerField(default=0, verbose_name='Shift')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='month_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycalendar.monthyear'),
        ),
    ]
