# Generated by Django 5.0.6 on 2024-07-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0008_monthyear_day_month_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
    ]
