# Generated by Django 5.0.6 on 2024-07-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0009_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['pk']},
        ),
    ]
