# Generated by Django 5.0.6 on 2024-07-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0011_alter_user_options_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthyear',
            name='days_amount',
            field=models.PositiveSmallIntegerField(default=31, verbose_name='Amount of days'),
        ),
        migrations.AddField(
            model_name='monthyear',
            name='month_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='monthyear',
            name='year',
            field=models.PositiveIntegerField(default=0, verbose_name='Year'),
        ),
    ]
