# Generated by Django 5.0.6 on 2024-07-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0014_remove_day_user_day_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='user',
        ),
        migrations.AddField(
            model_name='day',
            name='user',
            field=models.ManyToManyField(to='mycalendar.user'),
        ),
    ]
