# Generated by Django 5.0.6 on 2024-07-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0016_todo_day_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
