# Generated by Django 5.0.6 on 2024-08-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0017_remove_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='task_done',
            field=models.BooleanField(default=False, verbose_name='Done?'),
        ),
    ]
