# Generated by Django 5.0.6 on 2024-08-13 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0018_todo_task_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='task',
        ),
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycalendar.day'),
        ),
    ]
