# Generated by Django 5.0.6 on 2024-08-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0019_remove_day_task_todo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='task_done',
        ),
        migrations.AddField(
            model_name='todo',
            name='times',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number of times the task has been done'),
        ),
    ]
