# Generated by Django 5.0.6 on 2024-08-27 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0020_remove_todo_task_done_todo_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Material name')),
                ('overall_weight', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Net weight overall')),
                ('closed_cans', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Powder amount in closed cans')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Comment')),
                ('date', models.ForeignKey(limit_choices_to={'weekday': 'Четверг'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycalendar.day')),
            ],
            options={
                'ordering': ['-date', 'name'],
            },
        ),
    ]
