# Generated by Django 5.0.6 on 2024-09-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0024_drawing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printingregister',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='printingregister',
            name='duration',
        ),
        migrations.AddField(
            model_name='order',
            name='duration',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Order completion time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(max_length=30, verbose_name='Date of the order'),
        ),
    ]
