# Generated by Django 5.0.6 on 2024-09-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0025_remove_printingregister_date_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingregister',
            name='month',
            field=models.CharField(default=0, max_length=20, verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='printingregister',
            name='year',
            field=models.PositiveSmallIntegerField(default=2024, verbose_name='Year'),
        ),
    ]
