# Generated by Django 5.0.6 on 2024-09-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0028_alter_drawing_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='file',
            field=models.ImageField(max_length=1000, upload_to='uploads/', verbose_name='Drawing for detail ordered'),
        ),
    ]
