# Generated by Django 5.0.6 on 2024-09-18 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0029_alter_drawing_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Powder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Material name')),
                ('density', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Density of the material')),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycalendar.powder'),
        ),
    ]
