# Generated by Django 5.0.6 on 2024-09-18 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0030_powder_alter_material_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Volume of the model2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycalendar.powder'),
        ),
    ]
