# Generated by Django 5.0.6 on 2024-10-02 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0032_customer_alter_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Mini', 'Mini'), ('Mid', 'Mid'), ('Maxi', 'Maxi'), ('Общее', 'Общее')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='printer',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycalendar.printermodels'),
        ),
    ]
