# Generated by Django 5.0.6 on 2024-10-10 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0033_printermodels_alter_printer_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPatternForOperators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Job pattern')),
            ],
            options={
                'verbose_name_plural': 'Job Patterns For Operators',
            },
        ),
        migrations.AlterField(
            model_name='todo',
            name='times',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Number of times the task has been done'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycalendar.jobpatternforoperators'),
        ),
    ]
