# Generated by Django 5.0.6 on 2024-10-11 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0034_jobpatternforoperators_alter_todo_times_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200, verbose_name='Task')),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycalendar.day')),
            ],
        ),
    ]
