# Generated by Django 5.0.6 on 2024-10-17 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0037_remove_extratask_times_extratask_done_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operations', models.JSONField(verbose_name='Operations')),
                ('comments', models.CharField(blank=True, max_length=200, verbose_name='Comments on printing')),
                ('ready', models.BooleanField(default=False, verbose_name='Is it ready?')),
                ('datetime_end', models.DateTimeField(verbose_name='End date and time of the printing')),
                ('priority', models.CharField(choices=[('1', '1 приоритет'), ('2', '2 приоритет'), ('3', '3 приоритет'), ('0', 'Термичка')], max_length=1, verbose_name='Priority')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycalendar.powder')),
            ],
        ),
    ]
