# Generated by Django 5.0.6 on 2024-10-17 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0038_printingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPStandardOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Comments on printing')),
            ],
        ),
        migrations.AddField(
            model_name='printingplan',
            name='printer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycalendar.printer'),
        ),
        migrations.CreateModel(
            name='PPDrawing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(max_length=1000, upload_to='printing_plan/', verbose_name='Drawing for printing plan')),
                ('file_num', models.PositiveSmallIntegerField(verbose_name='File №')),
                ('pp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycalendar.printingplan')),
            ],
        ),
    ]
