# Generated by Django 5.0.6 on 2024-10-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0039_ppstandardoperations_printingplan_printer_ppdrawing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ppdrawing',
            options={'verbose_name': 'Drawing for Printing Plan', 'verbose_name_plural': 'Drawings for Printing Plan'},
        ),
        migrations.AlterModelOptions(
            name='ppstandardoperations',
            options={'verbose_name': 'Standard Operation for Printing Plan', 'verbose_name_plural': 'Standard Operations for Printing Plan'},
        ),
        migrations.AlterModelOptions(
            name='printingplan',
            options={'verbose_name': 'Printing Plan', 'verbose_name_plural': 'Printing Plan'},
        ),
    ]
