# Generated by Django 5.0.6 on 2024-10-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0040_alter_ppdrawing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppstandardoperations',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
