# Generated by Django 5.0.6 on 2024-10-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0041_alter_ppstandardoperations_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printingplan',
            options={'ordering': ['-id'], 'verbose_name': 'Printing Plan', 'verbose_name_plural': 'Printing Plan'},
        ),
        migrations.AlterField(
            model_name='printingplan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
