# Generated by Django 5.0.6 on 2024-10-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0043_alter_printingplan_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppdrawing',
            name='file_num',
        ),
        migrations.AddField(
            model_name='printingplan',
            name='file_num',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='File №'),
        ),
    ]
