# Generated by Django 5.0.6 on 2024-10-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0044_remove_ppdrawing_file_num_printingplan_file_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingplan',
            name='datetime_end',
            field=models.DateTimeField(blank=True, verbose_name='End date and time of the printing'),
        ),
        migrations.AlterField(
            model_name='printingplan',
            name='operations',
            field=models.JSONField(blank=True, verbose_name='Operations'),
        ),
    ]
