# Generated by Django 5.0.6 on 2024-10-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0045_alter_printingplan_datetime_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingplan',
            name='datetime_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date and time of the printing'),
        ),
        migrations.AlterField(
            model_name='printingplan',
            name='operations',
            field=models.JSONField(blank=True, null=True, verbose_name='Operations'),
        ),
    ]
