# Generated by Django 5.0.6 on 2024-11-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0050_readyorder_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularorder',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Is it hidden in the table'),
        ),
    ]
