# Generated by Django 5.0.6 on 2024-11-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0051_regularorder_hidden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegularOrder',
        ),
        migrations.AddField(
            model_name='order',
            name='regular',
            field=models.BooleanField(default=False, verbose_name='Is the order regular?'),
        ),
    ]
