# Generated by Django 5.0.6 on 2024-11-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0052_delete_regularorder_order_regular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=300, verbose_name='Comment'),
        ),
    ]
