# Generated by Django 5.0.6 on 2024-11-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0053_alter_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingregister',
            name='next_month',
            field=models.BooleanField(default=False, verbose_name='Will the order be completed next month?'),
        ),
    ]
