# Generated by Django 5.0.6 on 2024-11-11 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0054_printingregister_next_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularOrdersPattern',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='The name of the order')),
                ('amount', models.PositiveSmallIntegerField(default=1, verbose_name='Amount of details to produce')),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Volume of the model2')),
                ('cost', models.PositiveIntegerField(verbose_name='Order cost')),
                ('ready', models.BooleanField(default=False, verbose_name='Is the order ready?')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Comment')),
                ('date', models.CharField(max_length=30, verbose_name='Date of the order')),
                ('duration', models.PositiveSmallIntegerField(default=1, verbose_name='Order completion time')),
                ('regular', models.BooleanField(default=True, verbose_name='Is the order regular?')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycalendar.customer')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycalendar.powder')),
            ],
            options={
                'verbose_name': 'Regular Orders Pattern',
                'verbose_name_plural': 'Regular Orders Patterns',
            },
        ),
    ]
