# Generated by Django 5.0.6 on 2024-11-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0055_regularorderspattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularorderspattern',
            name='drawings',
            field=models.JSONField(blank=True, null=True, verbose_name='Drawings'),
        ),
    ]
